#!/usr/bin/env python3
"""
PrecisionPhage Pipeline - Publication Version
=============================================
Usage (run from SciFair2026/ directory):
  python scripts/run_pipeline.py
  python scripts/run_pipeline.py --thorough
  python scripts/run_pipeline.py --skip-download
  python scripts/run_pipeline.py --frozen-dataset data/results/frozen_dataset_v1.0.0.csv

All configuration is in scripts/config.yaml.  Do not edit this file for
configuration; it is pure orchestration.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent  # SciFair2026/


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
def setup_logging(results_dir: Path) -> logging.Logger:
    results_dir.mkdir(parents=True, exist_ok=True)
    log_path = results_dir / f"pipeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    root = logging.getLogger()
    for h in list(root.handlers):
        root.removeHandler(h)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(log_path, mode="w", encoding="utf-8"),
        ],
    )
    return logging.getLogger("pipeline")


# ---------------------------------------------------------------------------
# Config handling
# ---------------------------------------------------------------------------
def resolve_paths(cfg: dict) -> dict:
    for key, val in cfg["paths"].items():
        cfg["paths"][key] = (ROOT / val).resolve()

    if "fallback_paths" in cfg:
        for group, paths in list(cfg["fallback_paths"].items()):
            cfg["fallback_paths"][group] = [(ROOT / p).resolve() for p in paths]
    return cfg


# ---------------------------------------------------------------------------
# Dependency / version reporting
# ---------------------------------------------------------------------------
def check_dependencies() -> dict:
    deps = {"torch": False, "pyg": False, "xgb": False, "umap": False,
            "torch_version": None, "pyg_version": None}
    try:
        import torch
        deps["torch"] = True
        deps["torch_version"] = torch.__version__
        try:
            import torch_geometric
            deps["pyg"] = True
            deps["pyg_version"] = torch_geometric.__version__
        except ImportError:
            pass
    except ImportError:
        pass
    try:
        import xgboost  # noqa: F401
        deps["xgb"] = True
    except ImportError:
        pass
    try:
        import umap  # noqa: F401
        deps["umap"] = True
    except ImportError:
        pass
    return deps


def get_package_versions() -> dict:
    import importlib
    packages = ["numpy", "pandas", "sklearn", "scipy", "matplotlib",
                "seaborn", "xgboost", "torch", "torch_geometric", "yaml"]
    versions = {"python": sys.version.split()[0]}
    for pkg in packages:
        try:
            mod = importlib.import_module(pkg)
            versions[pkg] = getattr(mod, "__version__", "unknown")
        except ImportError:
            versions[pkg] = "not installed"
    return versions


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="PrecisionPhage Publication Pipeline")
    parser.add_argument("--config", default=str(Path(__file__).parent / "config.yaml"),
                        help="Path to config.yaml")
    parser.add_argument("--thorough", action="store_true",
                        help="More MC rounds and longer GNN training")
    parser.add_argument("--skip-download", action="store_true",
                        help="Skip external data downloads")
    parser.add_argument("--frozen-dataset", default=None,
                        help="Use a pre-frozen dataset CSV instead of rebuilding")
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    cfg = resolve_paths(cfg)

    if args.thorough:
        cfg["thorough_mode"] = True
        cfg["evaluation"]["n_mc_rounds"] = 30
        cfg["models"]["epochs"] = 400
        cfg["models"]["patience"] = 22

    # Ensure output directories exist
    for k in ("results_dir", "plots_dir", "features_dir"):
        cfg["paths"][k].mkdir(parents=True, exist_ok=True)

    log = setup_logging(cfg["paths"]["results_dir"])
    log.info("=" * 66)
    log.info("PrecisionPhage Pipeline - Publication Version")
    log.info(f"Run started: {datetime.now().isoformat()}")
    log.info("=" * 66)

    # Make scripts dir importable
    sys.path.insert(0, str(Path(__file__).parent))

    deps = check_dependencies()
    log.info(f"PyTorch: {deps['torch']} ({deps.get('torch_version', 'n/a')})")
    log.info(f"PyG:     {deps['pyg']} ({deps.get('pyg_version', 'n/a')})")
    log.info(f"XGBoost: {deps['xgb']}")
    log.info(f"UMAP:    {deps['umap']}")
    gnn_available = deps["torch"] and deps["pyg"]
    if not gnn_available:
        log.warning("GNN models unavailable - running classical ML only.")
        log.warning("To enable GNNs: pip install torch --index-url "
                    "https://download.pytorch.org/whl/cpu && pip install torch-geometric")

    run_meta = {
        "timestamp": datetime.now().isoformat(),
        "config": str(args.config),
        "thorough": args.thorough,
        "skip_download": args.skip_download,
        "frozen_dataset": args.frozen_dataset,
        "dependencies": deps,
        "package_versions": get_package_versions(),
        "seed": cfg["reproducibility"]["seed"],
        "dataset_version": cfg["reproducibility"]["dataset_version"],
        "platform": sys.platform,
    }
    meta_path = cfg["paths"]["results_dir"] / "run_metadata.json"
    meta_path.write_text(json.dumps(run_meta, indent=2, default=str), encoding="utf-8")

    t_total = time.time()

    # ------------------------------------------------------------------
    # 0. Verify manual inputs + fetch online sources
    # ------------------------------------------------------------------
    from fetch_data import verify_manual_inputs, fetch_all

    log.info("\n[0/9] Verifying manual inputs...")
    verify_manual_inputs(cfg)

    if not args.skip_download:
        log.info("[0/9] Fetching online data sources...")
        fetch_all(cfg)
    else:
        log.info("[0/9] Skipping online fetch (--skip-download).")
        # Still need PhagesDB cache and VHDB file when skipping network
        cache = Path(cfg["paths"]["phagesdb_cache"])
        vhdb = Path(cfg["paths"]["raw_dir"]) / "virushostdb_raw.tsv"
        if not cache.exists():
            log.warning("  phagesdb_records_cache.json missing — PhagesDB source will be empty.")
        if not vhdb.exists():
            log.warning("  virushostdb_raw.tsv missing — Virus-Host DB source will be empty.")

    # ------------------------------------------------------------------
    # 1. Dataset assembly
    # ------------------------------------------------------------------
    log.info("\n[1/9] Assembling dataset...")
    from data_collection import assemble_dataset, freeze_dataset, load_experimental_validation
    from build_labels import build_negatives

    if args.frozen_dataset:
        import pandas as pd
        log.info(f"  Loading frozen dataset: {args.frozen_dataset}")
        dataset = pd.read_csv(args.frozen_dataset)
        sha256 = hashlib.sha256(Path(args.frozen_dataset).read_bytes()).hexdigest()
        log.info(f"  Frozen dataset SHA-256: {sha256}")
        log.info(f"  Rows: {len(dataset)}, Phages: {dataset['phage'].nunique()}, "
                 f"Hosts: {dataset['host'].nunique()}")
    else:
        pos_df = assemble_dataset(cfg, skip_download=args.skip_download)
        dataset = build_negatives(pos_df, cfg, seed=cfg["reproducibility"]["seed"])
        sha256 = freeze_dataset(dataset, cfg["reproducibility"]["dataset_version"],
                                cfg["paths"]["results_dir"])

    # ------------------------------------------------------------------
    # 2. Held-out experimental validation
    # ------------------------------------------------------------------
    log.info("\n[2/9] Loading experimental validation set...")
    exp_val_df = load_experimental_validation(cfg)
    if exp_val_df is not None and len(exp_val_df) > 0:
        log.info(f"  Experimental validation: {len(exp_val_df)} pairs, "
                 f"{exp_val_df['label'].value_counts().to_dict()}")
    else:
        log.warning("  No experimental validation set found - skipping.")
        exp_val_df = None

    # ------------------------------------------------------------------
    # 3. Feature computation
    # ------------------------------------------------------------------
    log.info("\n[3/9] Computing genomic features...")
    from data_enrichment import compute_all_features
    dataset, phage_feat_df, host_feat_df, feature_meta = compute_all_features(
        dataset, cfg, seed=cfg["reproducibility"]["seed"])
    log.info(f"  Features per phage: {phage_feat_df.shape[1]}")
    log.info(f"  Pair-level features: {feature_meta['pair_features']}")

    # ------------------------------------------------------------------
    # 4. Build feature matrices
    # ------------------------------------------------------------------
    log.info("\n[4/9] Building feature matrices...")
    from model import build_feature_matrices
    matrices = build_feature_matrices(dataset, phage_feat_df, host_feat_df,
                                      feature_meta, cfg,
                                      seed=cfg["reproducibility"]["seed"])

    # ------------------------------------------------------------------
    # 5. Classical ML
    # ------------------------------------------------------------------
    log.info("\n[5/9] Training classical ML models...")
    from evaluation import (get_valid_species, run_classical_loso,
                            get_valid_genera)
    valid_species = get_valid_species(dataset, cfg)
    valid_genera = get_valid_genera(dataset, cfg)
    log.info(f"  Valid LOSO species: {len(valid_species)}")
    log.info(f"  Valid LOGO genera:  {len(valid_genera)}")

    clf_results = run_classical_loso(dataset, matrices, valid_species, cfg,
                                     seed=cfg["reproducibility"]["seed"])
    for name, res in clf_results.items():
        log.info(f"  {name}: LOSO mean AUC={res['mean_auc']:.4f}")

    # ------------------------------------------------------------------
    # 6. GNN models
    # ------------------------------------------------------------------
    gnn_results = {}
    if gnn_available:
        log.info("\n[6/9] Training GNN models (GAT + GraphSAGE)...")
        from gnn import run_gnn_pipeline
        for arch in ["GAT", "SAGE"]:
            log.info(f"  Running {arch}...")
            try:
                gnn_results[arch] = run_gnn_pipeline(
                    arch, dataset, matrices, valid_species, valid_genera, cfg,
                    seed=cfg["reproducibility"]["seed"])
                log.info(f"  {arch}: LOSO mean AUC={gnn_results[arch]['loso_mean']:.4f} "
                         f"+/- {gnn_results[arch]['loso_std']:.4f}")
            except Exception as e:
                log.exception(f"  {arch} pipeline failed: {e}")
    else:
        log.info("\n[6/9] Skipping GNN models (dependencies not available).")

    # ------------------------------------------------------------------
    # 7. Statistical tests
    # ------------------------------------------------------------------
    log.info("\n[7/9] Running statistical tests...")
    from statistical_tests import run_all_tests
    all_results = {**clf_results, **gnn_results}
    stat_results = run_all_tests(all_results, dataset, cfg,
                                 seed=cfg["reproducibility"]["seed"])
    log.info(f"  Pairwise tests: {len(stat_results['pairwise'])} comparisons")

    # 7b. Experimental validation
    if exp_val_df is not None:
        log.info("  Running experimental validation...")
        from evaluation import run_experimental_validation
        exp_results = run_experimental_validation(
            exp_val_df, dataset, matrices, all_results, cfg,
            seed=cfg["reproducibility"]["seed"])
        log.info(f"  Experimental validation AUC: "
                 f"{exp_results.get('best_auc', 0):.4f}")
    else:
        exp_results = None

    # ------------------------------------------------------------------
    # 8. Ablation studies
    # ------------------------------------------------------------------
    log.info("  Running ablation study...")
    from ablation_study import run_ablation, run_name_leakage_ablation
    ablation_results = run_ablation(dataset, matrices, valid_species, cfg,
                                    seed=cfg["reproducibility"]["seed"],
                                    gnn_available=gnn_available)

    log.info("  Running name-embedding leakage ablation...")
    name_ablation = run_name_leakage_ablation(
        dataset, matrices, valid_species, cfg,
        seed=cfg["reproducibility"]["seed"],
        gnn_available=gnn_available)
    log.info(f"  Name leakage ablation - AUC with names: "
             f"{name_ablation['with_names']:.4f}, "
             f"without names: {name_ablation['without_names']:.4f}, "
             f"with sanitized names: {name_ablation['sanitized_names']:.4f}")
    log.info(f"  Conclusion: {name_ablation['conclusion']}")

    # ------------------------------------------------------------------
    # 9. Plotting and summary
    # ------------------------------------------------------------------
    log.info("\n[8/9] Generating plots...")
    from plotting import generate_all_plots
    generate_all_plots(dataset, all_results, stat_results, ablation_results,
                       name_ablation, exp_results, cfg,
                       seed=cfg["reproducibility"]["seed"])

    log.info("\n[9/9] Generating summary documents...")
    from summary import generate_summary_documents
    generate_summary_documents(
        dataset=dataset,
        all_results=all_results,
        stat_results=stat_results,
        ablation_results=ablation_results,
        name_ablation=name_ablation,
        exp_results=exp_results,
        valid_species=valid_species,
        feature_meta=feature_meta,
        run_meta=run_meta,
        sha256=sha256,
        cfg=cfg,
    )

    elapsed = time.time() - t_total
    log.info(f"\n{'=' * 66}")
    log.info(f"Pipeline complete in {elapsed / 60:.1f} minutes.")
    log.info(f"Results:  {cfg['paths']['results_dir']}")
    log.info(f"Plots:    {cfg['paths']['plots_dir']}")
    log.info("")
    log.info("NEXT STEPS FOR PUBLICATION:")
    log.info("  1. Upload frozen_dataset_v*.csv + .sha256 to Zenodo - get a DOI")
    log.info("  2. Replace [ZENODO DOI] in results/methods_skeleton.md")
    log.info("  3. Upload scripts/ to a public GitHub repository")
    log.info("  4. Include config.yaml in supplementary materials")
    log.info("  5. Copy results/methods_skeleton.md into your paper Methods section")
    log.info("  6. Copy results/reproducibility_card.md into supplementary materials")
    log.info(f"{'=' * 66}")


if __name__ == "__main__":
    main()
